# ai_builder.gd
# ----------------------------------------------------------------------------
# Project Nexus - AI Builder screen (Phase MC14, step 14.1, request 16).
#
# The author-facing screen that fulfils request 16: "let me build my own AI
# general -- name it, pick an archetype, slide the personality / strategy /
# diplomacy / learning / difficulty knobs, and Export / Import / Duplicate /
# Reset / Randomize it." It is a THIN view, exactly like gui_editor / mod_editor:
#
#   * The AI MODEL is the pure, headless-tested AiProfile (MC12.1).
#   * ALL builder logic (new / archetype presets / seeded randomize / duplicate /
#     reset / export / import) lives in the pure AiBuilderUtil (MC14.1); this
#     scene only renders sliders and forwards edits there.
#   * A live summary (role / style / danger / tags) comes from
#     AiProfileSummaryUtil (MC12.4). Every visible string is a localization key.
#
# The panels are built PROGRAMMATICALLY so the view can never drift from a stale
# .tscn: one slider row per knob, generated by iterating AiProfile.CATEGORIES.
# The root .tscn only supplies a full-rect Control host.
#
# This screen edits a COSMETIC authoring artefact only (a saved profile file); it
# never mutates WorldState gameplay and never feeds the deterministic hash. The
# profile only influences the simulation once selected in match setup, and even
# then deterministically (the profile is a fixed input to the AI).
#
# CODE LANGUAGE POLICY: English-only identifiers/comments (ASCII); visible text
# via Localization.
# ----------------------------------------------------------------------------
extends Control

const EDITOR_HUB_SCENE: String = "res://scenes/editor_hub.tscn"
const SELF_SCENE: String = "res://scenes/ai_builder.tscn"

var _loc: Localization = null
var _settings: GameSettings = null

# The profile being built and the widgets that edit it.
var _profile: AiProfile = null
var _name_edit: LineEdit = null
var _archetype_option: OptionButton = null
var _summary_label: Label = null
var _status: Label = null
var _back_button: Button = null
# category -> { knob -> HSlider }
var _sliders: Dictionary = {}


func _ready() -> void:
	_settings = GameSettings.new(_world_state())
	_settings.load_from_file()
	_loc = Localization.new()
	_loc.load_all("res://localization")
	_loc.set_locale(_settings.get_locale())

	_profile = AiBuilderUtil.new_profile("custom_ai")
	_build_ui()
	_refresh_from_profile()


func _world_state() -> Object:
	# GameSettings tolerates a null world state; this editor only reads settings.
	return null


func _t(key: String) -> String:
	if _loc == null:
		return key
	return _loc.tr(key)


# --- UI construction --------------------------------------------------------

func _build_ui() -> void:
	var root: VBoxContainer = VBoxContainer.new()
	root.anchor_right = 1.0
	root.anchor_bottom = 1.0
	root.offset_left = 16
	root.offset_top = 16
	root.offset_right = -16
	root.offset_bottom = -16
	add_child(root)

	var title: Label = Label.new()
	title.text = _t("ui.aibuilder.title")
	root.add_child(title)

	# Name + archetype row.
	var head: HBoxContainer = HBoxContainer.new()
	root.add_child(head)
	var name_label: Label = Label.new()
	name_label.text = _t("ui.aibuilder.name")
	head.add_child(name_label)
	_name_edit = LineEdit.new()
	_name_edit.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	_name_edit.text_submitted.connect(func(_s: String) -> void: _commit_name())
	head.add_child(_name_edit)
	var arch_label: Label = Label.new()
	arch_label.text = _t("ui.aibuilder.archetype")
	head.add_child(arch_label)
	_archetype_option = OptionButton.new()
	for arch in AiBuilderUtil.ARCHETYPES:
		_archetype_option.add_item(_t("ui.aibuilder.arch." + arch))
	_archetype_option.item_selected.connect(_on_archetype_selected)
	head.add_child(_archetype_option)

	# Toolbar: randomize / duplicate / reset / export / import.
	var toolbar: HBoxContainer = HBoxContainer.new()
	root.add_child(toolbar)
	toolbar.add_child(_make_button(_t("ui.aibuilder.randomize"), _on_randomize))
	toolbar.add_child(_make_button(_t("ui.aibuilder.duplicate"), _on_duplicate))
	toolbar.add_child(_make_button(_t("ui.aibuilder.reset"), _on_reset))
	toolbar.add_child(_make_button(_t("ui.aibuilder.export"), _on_export))
	toolbar.add_child(_make_button(_t("ui.aibuilder.import"), _on_import))

	# Live summary line (role / style / danger / tags).
	_summary_label = Label.new()
	_summary_label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	root.add_child(_summary_label)

	# Scrollable slider grid: one labelled slider per knob, grouped by category.
	var scroll: ScrollContainer = ScrollContainer.new()
	scroll.size_flags_vertical = Control.SIZE_EXPAND_FILL
	root.add_child(scroll)
	var grid: VBoxContainer = VBoxContainer.new()
	grid.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	scroll.add_child(grid)
	for category in AiProfile.CATEGORIES:
		var header: Label = Label.new()
		header.text = _t("ui.aibuilder.cat." + category)
		grid.add_child(header)
		var cat_sliders: Dictionary = {}
		for knob in AiProfile.keys_for(category):
			cat_sliders[knob] = _make_slider_row(grid, category, knob)
		_sliders[category] = cat_sliders

	_status = Label.new()
	root.add_child(_status)

	_back_button = _make_button(_t("ui.menu.back"), _on_back)
	root.add_child(_back_button)


func _make_slider_row(parent: Control, category: String, knob: String) -> HSlider:
	var row: HBoxContainer = HBoxContainer.new()
	var label: Label = Label.new()
	label.text = _t("ui.aibuilder.knob." + knob)
	label.custom_minimum_size = Vector2(160, 0)
	row.add_child(label)
	var slider: HSlider = HSlider.new()
	slider.min_value = 0.0
	slider.max_value = 1.0
	slider.step = 0.01
	slider.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	slider.value_changed.connect(func(v: float) -> void: _on_slider_changed(category, knob, v))
	row.add_child(slider)
	parent.add_child(row)
	return slider


func _make_button(text: String, handler: Callable) -> Button:
	var b: Button = Button.new()
	b.text = text
	b.pressed.connect(handler)
	return b


# --- Sync view <-> model ----------------------------------------------------

# Push every model value into its slider + refresh the summary. Guarded so the
# programmatic value set does not re-fire the change handler into the model.
var _syncing: bool = false

func _refresh_from_profile() -> void:
	if _profile == null:
		return
	_syncing = true
	for category in AiProfile.CATEGORIES:
		var cat_sliders: Dictionary = _sliders.get(category, {})
		for knob in cat_sliders.keys():
			(cat_sliders[knob] as HSlider).value = _profile.get_value(category, knob)
	# Archetype dropdown selection.
	var idx: int = AiBuilderUtil.ARCHETYPES.find(_profile.archetype())
	if idx >= 0:
		_archetype_option.select(idx)
	_syncing = false
	_refresh_summary()


func _refresh_summary() -> void:
	if _summary_label == null or _profile == null:
		return
	var role: String = _t(AiProfileSummaryUtil.role_key(_profile))
	var style: String = _t(AiProfileSummaryUtil.style_key(_profile))
	var danger: String = _t(AiProfileSummaryUtil.danger_key(_profile))
	_summary_label.text = "%s / %s / %s" % [role, style, danger]


# --- Event handlers (forward to AiBuilderUtil) ------------------------------

func _on_slider_changed(category: String, knob: String, value: float) -> void:
	if _syncing:
		return
	AiBuilderUtil.set_knob(_profile, category, knob, value)
	_refresh_summary()


func _on_archetype_selected(index: int) -> void:
	if index < 0 or index >= AiBuilderUtil.ARCHETYPES.size():
		return
	AiBuilderUtil.apply_archetype(_profile, str(AiBuilderUtil.ARCHETYPES[index]))
	_refresh_from_profile()
	_set_status("")


func _on_randomize() -> void:
	# Seed the deterministic randomize from the current tick count so successive
	# presses differ, while any single seed stays reproducible in tests.
	var seed_value: int = int(Time.get_ticks_msec())
	_profile = AiBuilderUtil.randomize_profile(_profile.id(), seed_value)
	_refresh_from_profile()
	_set_status(_t("ui.aibuilder.status.randomized"))


func _on_duplicate() -> void:
	_profile = AiBuilderUtil.duplicate_profile(_profile, _profile.id() + "_copy")
	_commit_name_field()
	_refresh_from_profile()
	_set_status(_t("ui.aibuilder.status.duplicated"))


func _on_reset() -> void:
	AiBuilderUtil.reset_knobs(_profile)
	_refresh_from_profile()
	_set_status(_t("ui.aibuilder.status.reset"))


func _on_export() -> void:
	var data: Dictionary = AiBuilderUtil.export_dict(_profile)
	var path: String = _export_path()
	var f: FileAccess = FileAccess.open(path, FileAccess.WRITE)
	if f == null:
		_set_status(_t("ui.aibuilder.status.export_failed"))
		return
	f.store_string(JSON.stringify(data, "\t"))
	f.close()
	_set_status(_t("ui.aibuilder.status.exported"))


func _on_import() -> void:
	var path: String = _export_path()
	if not FileAccess.file_exists(path):
		_set_status(_t("ui.aibuilder.status.import_missing"))
		return
	var f: FileAccess = FileAccess.open(path, FileAccess.READ)
	if f == null:
		_set_status(_t("ui.aibuilder.status.import_failed"))
		return
	var text: String = f.get_as_text()
	f.close()
	var parsed = JSON.parse_string(text)
	if not (parsed is Dictionary):
		_set_status(_t("ui.aibuilder.status.import_failed"))
		return
	var res: Dictionary = AiBuilderUtil.import_dict(parsed)
	_profile = res["profile"]
	_refresh_from_profile()
	if bool(res["ok"]):
		_set_status(_t("ui.aibuilder.status.imported"))
	else:
		_set_status(_t("ui.aibuilder.status.import_invalid"))


func _commit_name() -> void:
	_commit_name_field()
	_refresh_summary()


# Store the name field text as the profile display-name key (raw, cosmetic).
func _commit_name_field() -> void:
	if _profile == null or _name_edit == null:
		return
	var raw: String = _name_edit.text.strip_edges()
	if not raw.is_empty():
		AiBuilderUtil.set_display_name_key(_profile, raw)


func _export_path() -> String:
	return "user://custom_ai." + AiProfile.PROFILE_EXTENSION


func _set_status(text: String) -> void:
	if _status != null:
		_status.text = text


# --- Back navigation (MB3 / NavService) -------------------------------------

func _on_back() -> void:
	_commit_name()
	get_tree().change_scene_to_file(EDITOR_HUB_SCENE)


func _notification(what: int) -> void:
	if what == NOTIFICATION_WM_GO_BACK_REQUEST:
		_on_back()
