# t006_acceptance.gd
# ----------------------------------------------------------------------------
# Project Nexus - T006 objective acceptance checker (author: Claude, Tech Lead).
# READ-ONLY FOR THE EXECUTOR: do not edit this file. Make every check PASS.
#
# Run:    godot --headless --path . --script res://tests/acceptance/t006_acceptance.gd
#         optional: -- --only=ABC   (run only the listed sections)
# Output: one line per check  "T006_CHECK PASS|FAIL <id> <message>"
#         final line           "T006_SUMMARY pass=<n> fail=<m>"
# Exit code 0 only when fail == 0.
#
# Every lookup is dynamic (load()/has_method/catalog reads) so this file parses
# on a tree where the features do not exist yet: a missing feature is a FAIL,
# never a crash. CODE LANGUAGE POLICY: English-only identifiers/comments.
# ----------------------------------------------------------------------------
extends SceneTree

const TR = preload("res://tests/test_runner.gd")

const MOD_ID: String = "frontier"
const MOD_DIR: String = "res://mods/frontier"
const PREFIX: String = "fr_"
const HQ_TYPE: String = "fr_citadel"
const DUEL_ID: String = "fr_river_valley"
const FOUR_ID: String = "fr_four_realms"
const ENERGY: String = "resource_energy"
const GOLD: String = "resource_basic"

# Vanilla behaviour lock: base catalogs only, hash after 600 ticks.
# Values are AFTER WP0 (belief-grid fix, DEC-017); see docs/ai/tasks/T006_PROMPT.md.
const VANILLA_GOLD: Dictionary = {
	"skirmish_basic": 853235305436049241,
	"skirmish_duel": -4480766952479341591,
	"skirmish_four_corners": -1523216689346447094,
}

var _pass: int = 0
var _fail: int = 0
var _only: String = ""


func _init() -> void:
	for a in OS.get_cmdline_user_args():
		if str(a).begins_with("--only="):
			_only = str(a).substr(7)
	var t0: int = Time.get_ticks_msec()
	_section("A", Callable(self, "_a_vanilla_lock"))
	_section("B", Callable(self, "_b_content"))
	_section("C", Callable(self, "_c_engine"))
	_section("D", Callable(self, "_d_playthrough"))
	_section("E", Callable(self, "_e_maps"))
	_section("F", Callable(self, "_f_ai"))
	_section("G", Callable(self, "_g_ui_render_docs"))
	print("T006_TIME ms=%d" % (Time.get_ticks_msec() - t0))
	print("T006_SUMMARY pass=%d fail=%d" % [_pass, _fail])
	quit(0 if _fail == 0 else 1)


func _section(letter: String, fn: Callable) -> void:
	if _only != "" and not _only.contains(letter):
		return
	print("---- T006 section %s ----" % letter)
	var t0: int = Time.get_ticks_msec()
	fn.call()
	print("T006_SECTION_TIME %s ms=%d" % [letter, Time.get_ticks_msec() - t0])


func _ok(cond: bool, id: String, msg: String) -> void:
	if cond:
		_pass += 1
		print("T006_CHECK PASS %s %s" % [id, msg])
	else:
		_fail += 1
		print("T006_CHECK FAIL %s %s" % [id, msg])


# --- harness helpers ---------------------------------------------------------

func _vanilla() -> Object:
	var n: Object = TR.TickHarness.new()
	GameBootstrap.register_modules(n)
	var dl: Object = n.data_loader
	for c in [["units", "units"], ["buildings", "buildings"], ["tech", "tech"],
			["difficulty", "difficulty_presets"], ["scenarios", "scenarios"], ["stats", "stats"]]:
		dl.load_catalog(str(c[0]), "res://data/" + str(c[1]))
	StatRegistry.reset_definitions()
	StatRegistry.load_definitions(dl.get_catalog("stats"))
	return n


func _full() -> Object:
	var n: Object = TR.TickHarness.new()
	GameBootstrap.register_modules(n)
	GameBootstrap.load_catalogs(n)
	return n


func _cat(n: Object, name: String) -> Dictionary:
	return n.data_loader.get_catalog(name)


func _fr_ids(cat: Dictionary) -> Array:
	var out: Array = []
	for k in cat.keys():
		if str(k).begins_with(PREFIX):
			out.append(str(k))
	out.sort()
	return out


func _fr_tech_nodes(n: Object) -> Dictionary:
	var out: Dictionary = {}
	var cat: Dictionary = _cat(n, "tech")
	var trees: Array = cat.keys()
	trees.sort()
	for tree_id in trees:
		var doc: Variant = cat[tree_id]
		if not (doc is Dictionary):
			continue
		for node in (doc as Dictionary).get("nodes", []):
			if node is Dictionary and str(node.get("id", "")).begins_with(PREFIX):
				out[str(node["id"])] = node
	return out


func _buildings(n: Object) -> Dictionary:
	return n.world_state.get_section("buildings").get("list", {})


func _units(n: Object) -> Dictionary:
	return n.world_state.get_section("units").get("list", {})


func _wallet(n: Object, owner: int) -> Dictionary:
	return n.world_state.get_section("economy").get("players", {}).get(str(owner), {})


func _researched(n: Object, owner: int) -> Array:
	return n.world_state.get_section("tech").get("players", {}).get(str(owner), {}).get("researched", [])


func _completed_types(n: Object, owner: int) -> Array:
	var out: Array = []
	var list: Dictionary = _buildings(n)
	for k in list.keys():
		var b: Dictionary = list[k]
		if int(b.get("owner", -1)) == owner and int(b.get("health", 0)) > 0 \
				and int(b.get("construction_remaining", 0)) <= 0 and not out.has(str(b.get("type", ""))):
			out.append(str(b.get("type", "")))
	out.sort()
	return out


func _first_building_of(n: Object, owner: int, type: String) -> Dictionary:
	var list: Dictionary = _buildings(n)
	var keys: Array = list.keys()
	keys.sort_custom(func(a, b): return int(a) < int(b))
	for k in keys:
		var b: Dictionary = list[k]
		if int(b.get("owner", -1)) == owner and str(b.get("type", "")) == type and int(b.get("health", 0)) > 0:
			return b
	return {}


func _req_buildings(entry: Dictionary) -> Array:
	var r: Variant = entry.get("requires", {})
	if r is Dictionary:
		return (r as Dictionary).get("buildings", [])
	return []


func _req_tech(entry: Dictionary) -> Array:
	var r: Variant = entry.get("requires", {})
	if r is Dictionary:
		return (r as Dictionary).get("tech", [])
	return []


func _flat_scenario(w: int, h: int, players: int, rules: Dictionary = {}) -> Dictionary:
	var rows: Array = []
	for y in range(h):
		rows.append(".".repeat(w))
	var ps: Array = []
	for o in range(players):
		ps.append({ "owner": o, "is_human": true, "start_resources": { GOLD: 100000, ENERGY: 100000 } })
	var blds: Array = [
		{ "type": HQ_TYPE, "owner": 0, "x": 2, "y": 2 },
		{ "type": HQ_TYPE, "owner": 1, "x": w - 3, "y": h - 3 },
	]
	var sc: Dictionary = { "id": "t006_flat", "random_seed": 7, "hq_type": HQ_TYPE,
		"map": { "rows": rows }, "players": ps, "buildings": blds, "units": [] }
	if not rules.is_empty():
		sc["rules"] = rules
	return sc


class Rec extends RefCounted:
	var events: Array = []
	var spawned: Dictionary = {}   # owner(str) -> { type: true }
	var techs: Dictionary = {}     # owner(str) -> { node: true }

	func on_ev(event_name: String, payload: Dictionary) -> void:
		events.append([event_name, payload.duplicate(true)])
		if event_name == "units.spawned":
			var o: String = str(int(payload.get("owner", -1)))
			if not spawned.has(o):
				spawned[o] = {}
			spawned[o][str(payload.get("type", ""))] = true
		elif event_name == "tech.research_completed":
			var o2: String = str(int(payload.get("owner", -1)))
			if not techs.has(o2):
				techs[o2] = {}
			techs[o2][str(payload.get("node_id", ""))] = true

	func reasons(event_name: String) -> Array:
		var out: Array = []
		for e in events:
			if e[0] == event_name:
				out.append(str((e[1] as Dictionary).get("reason", "")))
		return out

	func count(event_name: String) -> int:
		var c: int = 0
		for e in events:
			if e[0] == event_name:
				c += 1
		return c


func _rec(n: Object) -> Rec:
	var r: Rec = Rec.new()
	for ev in ["units.spawned", "tech.research_completed", "buildings.build_rejected",
			"economy.build_rejected", "tech.research_rejected", "combat.attack", "units.died"]:
		n.subscribe(ev, r, "on_ev")
	return r


# =============================================================================
# A. Vanilla behaviour lock
# =============================================================================

func _a_vanilla_lock() -> void:
	var ids: Array = VANILLA_GOLD.keys()
	ids.sort()
	for id in ids:
		var v: Object = _vanilla()
		ScenarioLoader.apply_scenario(v, v.data_loader.get_entry("scenarios", id))
		v.run_ticks(600)
		var h: int = StateHasher.hash_world(v.world_state)
		_ok(h == int(VANILLA_GOLD[id]), "A1." + id, "vanilla hash after 600 ticks matches post-WP0 golden (got %d)" % h)
		var f: Object = _full()
		ScenarioLoader.apply_scenario(f, f.data_loader.get_entry("scenarios", id))
		f.run_ticks(600)
		var diff: Array = []
		var names: Array = v.world_state.get_all_section_names()
		for s in f.world_state.get_all_section_names():
			if not names.has(s):
				names.append(s)
		for s in names:
			if s == "mods" or s == "ui_prefs" or s == "lockstep" or s == "local_selection":
				continue
			if StateHasher.hash_variant(v.world_state.get_section(s)) != StateHasher.hash_variant(f.world_state.get_section(s)):
				diff.append(s)
		_ok(diff.is_empty(), "A2." + id, "enabling the frontier mod changes no simulation section %s" % str(diff))
		var mods_loaded: Array = f.world_state.get_section("mods").get("loaded", [])
		_ok(mods_loaded.has(MOD_ID), "A3." + id, "frontier mod is loaded by default %s" % str(mods_loaded))


# =============================================================================
# B. Content: catalog completeness, tree shape, balance, localization
# =============================================================================

func _b_content() -> void:
	var manifest: Variant = JSON.parse_string(FileAccess.get_file_as_string(MOD_DIR + "/mod.json")) \
			if FileAccess.file_exists(MOD_DIR + "/mod.json") else null
	_ok(manifest is Dictionary, "B01", "mods/frontier/mod.json parses")
	if not (manifest is Dictionary):
		return
	var m: Dictionary = manifest
	_ok(str(m.get("id", "")) == MOD_ID and bool(m.get("enabled", false)), "B02", "manifest id=frontier enabled=true")
	var prov: Dictionary = m.get("provides", {})
	for c in ["units", "buildings", "tech", "scenarios"]:
		_ok(prov.has(c) and (prov[c] as Array).size() > 0, "B03." + c, "manifest provides %s" % c)

	var n: Object = _full()
	var units: Dictionary = _cat(n, "units")
	var blds: Dictionary = _cat(n, "buildings")
	var uids: Array = _fr_ids(units)
	var bids: Array = _fr_ids(blds)
	var techs: Dictionary = _fr_tech_nodes(n)
	_ok(uids.size() >= 10, "B04", "at least 10 fr_ units (%d)" % uids.size())
	_ok(bids.size() >= 10, "B05", "at least 10 fr_ buildings (%d)" % bids.size())
	_ok(techs.size() >= 10, "B06", "at least 10 fr_ tech nodes (%d)" % techs.size())
	_ok(blds.has(HQ_TYPE), "B07", "fr_citadel exists")
	if uids.is_empty() or bids.is_empty():
		return

	var cats: Dictionary = {}
	var bad_units: Array = []
	for id in uids:
		var u: Dictionary = units[id]
		var st: Dictionary = u.get("stats", {})
		var ok: bool = int(u.get("build_time_ticks", 0)) > 0 and int((u.get("cost", {}) as Dictionary).get(GOLD, 0)) > 0
		for k in ["health", "attack_damage", "attack_range", "vision_range", "move_speed"]:
			ok = ok and int(st.get(k, 0)) > 0
		var vis: Variant = u.get("visual", null)
		ok = ok and vis is Dictionary and (vis as Dictionary).has("shape") and (vis as Dictionary).has("color")
		ok = ok and str(u.get("display_name_key", "")) != ""
		if not ok:
			bad_units.append(id)
		cats[str(u.get("category", ""))] = true
	_ok(bad_units.is_empty(), "B08", "every fr_ unit has cost/build time/5 stats/visual/name key %s" % str(bad_units))
	_ok(cats.size() >= 4, "B09", "fr_ units span >= 4 categories %s" % str(cats.keys()))

	var producible: Dictionary = {}
	var bad_blds: Array = []
	var defense: int = 0
	var energy_producer: bool = false
	for id in bids:
		var b: Dictionary = blds[id]
		var ok2: bool = int((b.get("stats", {}) as Dictionary).get("health", 0)) > 0 and str(b.get("display_name_key", "")) != ""
		var vis2: Variant = b.get("visual", null)
		ok2 = ok2 and vis2 is Dictionary and (vis2 as Dictionary).has("color")
		if id != HQ_TYPE:
			ok2 = ok2 and int(b.get("build_time_ticks", 0)) > 0 and int((b.get("cost", {}) as Dictionary).get(GOLD, 0)) > 0
		for uid in b.get("buildable_units", []):
			producible[str(uid)] = true
			if not units.has(str(uid)):
				ok2 = false
		var ups: Variant = b.get("upgrades", {})
		if ups is Dictionary:
			for lk in (ups as Dictionary).keys():
				var lv: Variant = ups[lk]
				if lv is Dictionary:
					for uid2 in ((lv as Dictionary).get("effects", {}) as Dictionary).get("buildable_units_add", []):
						producible[str(uid2)] = true
		if int((b.get("stats", {}) as Dictionary).get("attack_damage", 0)) > 0:
			defense += 1
		if int((b.get("produces", {}) as Dictionary).get(ENERGY, 0)) > 0:
			energy_producer = true
		if not ok2:
			bad_blds.append(id)
	_ok(bad_blds.is_empty(), "B10", "every fr_ building has health/name/visual/cost/time and valid buildable_units %s" % str(bad_blds))
	var unprod: Array = []
	for id in uids:
		if not producible.has(id):
			unprod.append(id)
	_ok(unprod.is_empty(), "B11", "every fr_ unit is producible by some fr_ building %s" % str(unprod))
	_ok(defense >= 2, "B12", ">= 2 defensive fr_ buildings with attack_damage (%d)" % defense)
	_ok(energy_producer, "B13", "some fr_ building produces resource_energy")
	var energy_units: int = 0
	var tech_gated_units: int = 0
	for id in uids:
		if int((units[id].get("cost", {}) as Dictionary).get(ENERGY, 0)) > 0:
			energy_units += 1
		if not _req_tech(units[id]).is_empty():
			tech_gated_units += 1
	_ok(energy_units >= 3, "B14", ">= 3 fr_ units cost resource_energy (%d)" % energy_units)
	_ok(tech_gated_units >= 2, "B15", ">= 2 fr_ units require a tech (%d)" % tech_gated_units)

	var bad_refs: Array = []
	for id in bids:
		for r in _req_buildings(blds[id]):
			if not blds.has(str(r)):
				bad_refs.append(id + "->" + str(r))
		for t in _req_tech(blds[id]):
			if not techs.has(str(t)):
				bad_refs.append(id + "->" + str(t))
	for id in uids:
		for r in _req_buildings(units[id]):
			if not blds.has(str(r)):
				bad_refs.append(id + "->" + str(r))
		for t in _req_tech(units[id]):
			if not techs.has(str(t)):
				bad_refs.append(id + "->" + str(t))
	for tid in techs.keys():
		for r in (techs[tid] as Dictionary).get("requires", []):
			if not techs.has(str(r)):
				bad_refs.append(str(tid) + "->" + str(r))
		for rb in (techs[tid] as Dictionary).get("requires_buildings", []):
			if not blds.has(str(rb)):
				bad_refs.append(str(tid) + "->" + str(rb))
	_ok(bad_refs.is_empty(), "B16", "all requires references resolve %s" % str(bad_refs))
	_ok(_req_buildings(blds.get(HQ_TYPE, {})).is_empty() and _req_tech(blds.get(HQ_TYPE, {})).is_empty(), "B17",
		"fr_citadel has no prerequisites")

	var depth: Dictionary = {}
	for _round in range(64):
		var changed: bool = false
		for id in bids:
			var d: int = 0
			var known: bool = true
			for r in _req_buildings(blds[id]):
				if not depth.has(str(r)):
					known = false
				else:
					d = max(d, int(depth[str(r)]) + 1)
			if known and (not depth.has(id) or int(depth[id]) != d):
				depth[id] = d
				changed = true
		if not changed:
			break
	var cyclic: bool = false
	for id in bids:
		if not depth.has(id):
			cyclic = true
	var maxd: int = 0
	for id in depth.keys():
		maxd = max(maxd, int(depth[id]))
	_ok(not cyclic, "B18", "building prerequisite graph is acyclic and fully reachable from fr_citadel")
	_ok(maxd >= 4, "B19", "building tree depth >= 4 (longest chain %d)" % maxd)

	var tdepth: Dictionary = {}
	for _round2 in range(64):
		for tid in techs.keys():
			var d2: int = 0
			var known2: bool = true
			for r in (techs[tid] as Dictionary).get("requires", []):
				if not tdepth.has(str(r)):
					known2 = false
				else:
					d2 = max(d2, int(tdepth[str(r)]) + 1)
			if known2:
				tdepth[tid] = d2
	var tmax: int = 0
	for tid in tdepth.keys():
		tmax = max(tmax, int(tdepth[tid]))
	_ok(tdepth.size() == techs.size(), "B20", "tech graph acyclic")
	_ok(tmax >= 2, "B21", "tech tree depth >= 3 levels (max index %d)" % tmax)
	var tech_bgated: int = 0
	var bad_tech: Array = []
	for tid in techs.keys():
		var tn: Dictionary = techs[tid]
		if not (tn.get("requires_buildings", []) as Array).is_empty():
			tech_bgated += 1
		if int((tn.get("cost", {}) as Dictionary).get(GOLD, 0)) <= 0 or int(tn.get("research_time_ticks", 0)) <= 0 \
				or (tn.get("effects", []) as Array).is_empty() or str(tn.get("display_name_key", "")) == "":
			bad_tech.append(tid)
	_ok(tech_bgated >= 5, "B22", ">= 5 fr_ techs require a building (%d)" % tech_bgated)
	_ok(bad_tech.is_empty(), "B23", "every fr_ tech has cost/time/effects/name %s" % str(bad_tech))

	var dominated: Array = []
	var values: Array = []
	var vmap: Dictionary = {}
	for a in uids:
		var sa: Dictionary = units[a].get("stats", {})
		var ca: int = _total_cost(units[a])
		var va: float = float(int(sa.get("health", 1)) * int(sa.get("attack_damage", 1))) \
				* (1.0 + 0.25 * float(int(sa.get("attack_range", 1)) - 1)) / float(max(1, ca))
		values.append(va)
		vmap[a] = va
		for b2 in uids:
			if a == b2:
				continue
			var sb: Dictionary = units[b2].get("stats", {})
			var ge: bool = true
			var gt: bool = false
			for k in ["health", "attack_damage", "attack_range", "vision_range", "move_speed"]:
				if int(sa.get(k, 0)) < int(sb.get(k, 0)):
					ge = false
				elif int(sa.get(k, 0)) > int(sb.get(k, 0)):
					gt = true
			var cb: int = _total_cost(units[b2])
			if ca < cb:
				gt = true
			if ge and ca <= cb and gt:
				dominated.append(b2 + "<" + a)
	_ok(dominated.is_empty(), "B24", "no fr_ unit strictly dominates another %s" % str(dominated))
	values.sort()
	var med: float = float(values[values.size() / 2]) if not values.is_empty() else 1.0
	var outliers: Array = []
	for id in uids:
		var r2: float = float(vmap[id]) / max(0.0001, med)
		if r2 < 0.25 or r2 > 4.0:
			outliers.append("%s:%.2f" % [id, r2])
	_ok(outliers.is_empty(), "B25", "every fr_ unit value-per-cost within 0.25x..4x of median %s" % str(outliers))

	var en: Dictionary = _loc_table("res://localization/en.json")
	var fa: Dictionary = _loc_table("res://localization/fa.json")
	var keys: Array = []
	for id in uids:
		keys.append(str(units[id].get("display_name_key", "")))
	for id in bids:
		keys.append(str(blds[id].get("display_name_key", "")))
	for tid in techs.keys():
		keys.append(str(techs[tid].get("display_name_key", "")))
	for sid in [DUEL_ID, FOUR_ID]:
		var sc: Variant = n.data_loader.get_entry("scenarios", sid)
		if sc is Dictionary:
			keys.append(str((sc as Dictionary).get("display_name_key", "")))
	keys.append("resource." + ENERGY + ".name")
	keys.append("resource." + GOLD + ".name")
	var miss: Array = []
	for k in keys:
		if k == "" or not en.has(k) or not fa.has(k) or str(fa.get(k, "")) == str(en.get(k, "")):
			miss.append(k)
	_ok(miss.is_empty(), "B26", "every fr_ name key + resource names exist in en and fa (fa translated) %s" % str(miss))


func _total_cost(entry: Dictionary) -> int:
	var c: Dictionary = entry.get("cost", {})
	var t: int = 0
	for k in c.keys():
		t += int(c[k])
	return t


func _loc_table(path: String) -> Dictionary:
	var d: Variant = JSON.parse_string(FileAccess.get_file_as_string(path))
	if d is Dictionary:
		return (d as Dictionary).get("strings", {})
	return {}


# =============================================================================
# C. Engine contracts
# =============================================================================

func _c_engine() -> void:
	var pu_path: String = "res://core/prereq_util.gd"
	var pu: Script = load(pu_path) if ResourceLoader.exists(pu_path) else null
	_ok(pu != null, "C01", "core/prereq_util.gd (class_name PrereqUtil) exists")
	if pu != null:
		var m1: Variant = pu.call("missing", { "buildings": ["b2", "b1"], "tech": ["t1"] }, ["b1"], [])
		_ok(m1 is Array and m1 == ["building:b2", "tech:t1"], "C02", "PrereqUtil.missing sorted 'building:'/'tech:' ids (got %s)" % str(m1))
		var m2: Variant = pu.call("missing", {}, [], [])
		_ok(m2 is Array and (m2 as Array).is_empty(), "C03", "PrereqUtil.missing({}) is empty")
		var m3: Variant = pu.call("missing", null, [], [])
		_ok(m3 is Array and (m3 as Array).is_empty(), "C04", "PrereqUtil.missing(null) is empty (robust)")
		var list: Dictionary = {
			"5": { "owner": 0, "type": "b", "health": 10, "construction_remaining": 0 },
			"3": { "owner": 0, "type": "a", "health": 10, "construction_remaining": 0 },
			"4": { "owner": 0, "type": "c", "health": 10, "construction_remaining": 5 },
			"6": { "owner": 1, "type": "d", "health": 10, "construction_remaining": 0 },
			"7": { "owner": 0, "type": "e", "health": 0, "construction_remaining": 0 },
			"8": { "owner": 0, "type": "a", "health": 10, "construction_remaining": 0 },
		}
		var ct: Variant = pu.call("owner_completed_building_types", list, 0)
		_ok(ct is Array and ct == ["a", "b"], "C05", "owner_completed_building_types = sorted unique completed alive (got %s)" % str(ct))
	else:
		for cid in ["C02", "C03", "C04", "C05"]:
			_ok(false, cid, "needs PrereqUtil")
	_ok(_const_of("res://modules/map/map_module.gd", "TERRAIN_FOREST") == 3, "C06", "MapModule.TERRAIN_FOREST == 3")

	var n: Object = _full()
	var sc: Dictionary = { "id": "t006_rows", "random_seed": 1, "map": { "rows": ["..#~", "T..."] },
		"players": [], "buildings": [], "units": [] }
	ScenarioLoader.apply_scenario(n, sc)
	var ms: Dictionary = n.world_state.get_section("map")
	_ok(int(ms.get("width", 0)) == 4 and int(ms.get("height", 0)) == 2, "C07",
		"map.rows sets width/height (got %dx%d)" % [int(ms.get("width", 0)), int(ms.get("height", 0))])
	var tl: Array = []
	for t in ms.get("tiles", []):
		tl.append(int(t))
	_ok(tl == [0, 0, 1, 2, 3, 0, 0, 0], "C08", "map.rows chars . # ~ T -> 0 1 2 3 (got %s)" % str(tl))
	var mm: Object = n.get_module("map")
	_ok(mm != null and tl.size() == 8 and not mm.is_walkable(0, 1) and mm.is_walkable(1, 1), "C09", "forest is not walkable")

	var n2: Object = _full()
	var sc2: Dictionary = _flat_scenario(20, 14, 2)
	sc2["buildings"] = []
	ScenarioLoader.apply_scenario(n2, sc2)
	var types: Array = []
	for k in _buildings(n2).keys():
		types.append(str(_buildings(n2)[k].get("type", "")))
	_ok(types.size() == 2 and types.count(HQ_TYPE) == 2, "C10", "scenario hq_type places auto-HQs of that type (got %s)" % str(types))

	# Vanilla shape locks (independent of the mod content).
	var v: Object = _vanilla()
	ScenarioLoader.apply_scenario(v, v.data_loader.get_entry("scenarios", "skirmish_duel"))
	v.run_ticks(5)
	var vb: Dictionary = _buildings(v)
	var shape_ok: bool = not vb.is_empty()
	for k in vb.keys():
		var keys: Array = (vb[k] as Dictionary).keys()
		keys.sort()
		if keys != ["build_queue", "buildable_units", "construction_remaining", "health", "id", "level",
				"max_health", "owner", "produces", "territory_radius", "type", "x", "y"]:
			shape_ok = false
	_ok(shape_ok, "C19", "vanilla building record keys unchanged")
	var v2: Object = _vanilla()
	ScenarioLoader.apply_scenario(v2, v2.data_loader.get_entry("scenarios", "skirmish_basic"))
	_ok(not v2.world_state.has_section("rules"), "C23", "no 'rules' section is created for scenarios without rules")

	if not _cat(n2, "buildings").has(HQ_TYPE):
		for cid in ["C11", "C12", "C13", "C14", "C15", "C16", "C17", "C18", "C20", "C21", "C22"]:
			_ok(false, cid, "needs fr_citadel")
		return
	var blds: Dictionary = _cat(n2, "buildings")
	var units: Dictionary = _cat(n2, "units")
	var techs: Dictionary = _fr_tech_nodes(n2)

	var gated: String = ""
	for id in _fr_ids(blds):
		var rb: Array = _req_buildings(blds[id])
		if not rb.is_empty() and not (rb.size() == 1 and str(rb[0]) == HQ_TYPE):
			gated = id
			break
	var n3: Object = _full()
	ScenarioLoader.apply_scenario(n3, _flat_scenario(20, 14, 2))
	var r3: Rec = _rec(n3)
	var gold_before: int = int(_wallet(n3, 0).get(GOLD, 0))
	n3.issue_command("build_building", 0, { "type": gated, "owner": 0, "x": 8, "y": 8 }, 1)
	n3.run_ticks(3)
	_ok(gated != "" and r3.reasons("buildings.build_rejected").has("missing_prerequisite"), "C11",
		"build_building without prerequisite rejected 'missing_prerequisite' (%s)" % gated)
	_ok(gated != "" and int(_wallet(n3, 0).get(GOLD, 0)) == gold_before and _first_building_of(n3, 0, gated).is_empty(), "C12",
		"rejected building costs nothing and places nothing")
	var t1: String = ""
	for id in _fr_ids(blds):
		if id != HQ_TYPE and _req_buildings(blds[id]) == [HQ_TYPE] and _req_tech(blds[id]).is_empty():
			t1 = id
			break
	n3.issue_command("build_building", 0, { "type": t1, "owner": 0, "x": 6, "y": 6 }, 1)
	n3.run_ticks(3)
	_ok(t1 != "" and not _first_building_of(n3, 0, t1).is_empty(), "C13", "tier-1 building with met prerequisite is accepted (%s)" % t1)

	var gu: String = ""
	var gu_b: String = ""
	for id in _fr_ids(units):
		if not _req_tech(units[id]).is_empty():
			for bid in _fr_ids(blds):
				if (blds[bid].get("buildable_units", []) as Array).has(id):
					gu = id
					gu_b = bid
					break
		if gu != "":
			break
	var bid_placed: int = n3.get_module("buildings").place_building(gu_b, 0, 10, 4) if gu_b != "" else -1
	if bid_placed >= 0:
		n3.get_module("buildings").call("_buildings")[str(bid_placed)]["construction_remaining"] = 0
	var g2: int = int(_wallet(n3, 0).get(GOLD, 0))
	n3.issue_command("build_unit", 0, { "owner": 0, "building_id": bid_placed, "unit_type": gu }, 1)
	n3.run_ticks(3)
	_ok(gu != "" and r3.reasons("economy.build_rejected").has("missing_prerequisite") and int(_wallet(n3, 0).get(GOLD, 0)) == g2,
		"C14", "build_unit for tech-gated unit without the tech rejected 'missing_prerequisite', no cost (%s@%s)" % [gu, gu_b])

	var gt: String = ""
	var tkeys: Array = techs.keys()
	tkeys.sort()
	for tid in tkeys:
		var tn: Dictionary = techs[tid]
		var rbs: Array = tn.get("requires_buildings", [])
		if (tn.get("requires", []) as Array).is_empty() and not rbs.is_empty() and not rbs.has(HQ_TYPE):
			gt = str(tid)
			break
	n3.issue_command("research_tech", 0, { "owner": 0, "node_id": gt }, 1)
	n3.run_ticks(3)
	_ok(gt != "" and r3.reasons("tech.research_rejected").has("missing_prerequisite"), "C15",
		"research without requires_buildings rejected 'missing_prerequisite' (%s)" % gt)

	var tower: String = ""
	for id in _fr_ids(blds):
		if int((blds[id].get("stats", {}) as Dictionary).get("attack_damage", 0)) > 0:
			tower = id
			break
	var n4: Object = _full()
	ScenarioLoader.apply_scenario(n4, _flat_scenario(20, 14, 2))
	var r4: Rec = _rec(n4)
	var tid4: int = n4.get_module("buildings").place_building(tower, 0, 8, 7) if tower != "" else -1
	if tid4 >= 0:
		n4.get_module("buildings").call("_buildings")[str(tid4)]["construction_remaining"] = 0
	var victim: String = _fr_ids(units)[0] if not _fr_ids(units).is_empty() else "soldier"
	var vid: int = n4.get_module("units").spawn_unit(victim, 1, 8, 8)
	n4.run_ticks(60)
	var hit: bool = false
	for e in r4.events:
		if e[0] == "combat.attack" and int((e[1] as Dictionary).get("attacker", -1)) == tid4 \
				and int((e[1] as Dictionary).get("target", -1)) == vid:
			hit = true
	_ok(tower != "" and hit, "C16", "defensive building attacks an adjacent enemy unit (combat.attack attacker=%d)" % tid4)
	var vrec: Dictionary = _units(n4).get(str(vid), {})
	_ok(hit and (vrec.is_empty() or int(vrec.get("health", 0)) < int(vrec.get("max_health", 0))), "C17", "the enemy unit took damage")
	var hqrec: Dictionary = _first_building_of(n4, 0, HQ_TYPE)
	_ok(not hqrec.is_empty() and not hqrec.has("attack_damage"), "C18", "non-attacking building records carry no attack_damage key (vanilla shape kept)")

	var wall: String = ""
	for id in _fr_ids(blds):
		if blds[id].has("counts_for_survival") and not bool(blds[id]["counts_for_survival"]):
			wall = id
			break
	var n5: Object = _full()
	ScenarioLoader.apply_scenario(n5, _flat_scenario(20, 14, 2))
	if wall != "":
		n5.get_module("buildings").place_building(wall, 0, 5, 5)
	n5.get_module("buildings").destroy_building(int(_first_building_of(n5, 0, HQ_TYPE).get("id", -1)))
	n5.run_ticks(30)
	var vic: Object = n5.get_module("victory")
	_ok(wall != "" and vic.is_over() and vic.winner() == 1, "C20",
		"a player left with only counts_for_survival:false buildings is eliminated (%s)" % wall)

	var n6: Object = _full()
	ScenarioLoader.apply_scenario(n6, _flat_scenario(20, 14, 2, { "pop_cap": 2 }))
	var r6: Rec = _rec(n6)
	var cheap: String = ""
	var hq6: Dictionary = _first_building_of(n6, 0, HQ_TYPE)
	for uid in hq6.get("buildable_units", []):
		if _req_tech(units.get(str(uid), {})).is_empty() and _req_buildings(units.get(str(uid), {})).is_empty():
			cheap = str(uid)
			break
	if cheap != "":
		n6.get_module("units").spawn_unit(cheap, 0, 5, 9)
		n6.get_module("units").spawn_unit(cheap, 0, 6, 9)
		n6.issue_command("build_unit", 0, { "owner": 0, "building_id": int(hq6.get("id", -1)), "unit_type": cheap }, 1)
		n6.run_ticks(3)
	_ok(cheap != "" and r6.reasons("economy.build_rejected").has("pop_cap"), "C21", "rules.pop_cap rejects production at the cap with reason 'pop_cap'")
	_ok(int(n6.world_state.get_section("rules").get("pop_cap", 0)) == 2 if n6.world_state.has_section("rules") else false, "C22",
		"scenario rules are stored in world_state section 'rules'")


func _const_of(path: String, name: String) -> int:
	var s: Script = load(path)
	if s == null:
		return -1
	var cm: Dictionary = s.get_script_constant_map()
	return int(cm.get(name, -1))


# =============================================================================
# D. Full-tree playthrough: a human can build every building, research every
#    tech and produce every unit using only player commands.
# =============================================================================

func _d_playthrough() -> void:
	var n: Object = _full()
	var blds: Dictionary = _cat(n, "buildings")
	if not blds.has(HQ_TYPE):
		for cid in ["D01", "D02", "D03", "D04", "D05"]:
			_ok(false, cid, "fr_citadel missing")
		return
	var sc: Dictionary = _flat_scenario(40, 30, 2)
	sc["buildings"] = [
		{ "type": HQ_TYPE, "owner": 0, "x": 6, "y": 6 },
		{ "type": HQ_TYPE, "owner": 1, "x": 37, "y": 27 },
	]
	ScenarioLoader.apply_scenario(n, sc)
	var rec: Rec = _rec(n)
	var units: Dictionary = _cat(n, "units")
	var bids: Array = _fr_ids(blds)
	var uids: Array = _fr_ids(units)
	var techs: Dictionary = _fr_tech_nodes(n)
	var tids: Array = techs.keys()
	tids.sort()
	var pending_b: Dictionary = {}
	for step in range(400):
		var done_types: Array = _completed_types(n, 0)
		var researched: Array = _researched(n, 0)
		for id in bids:
			if done_types.has(id) or pending_b.has(id):
				continue
			var ok: bool = true
			for r in _req_buildings(blds[id]):
				ok = ok and done_types.has(str(r))
			for t in _req_tech(blds[id]):
				ok = ok and researched.has(str(t))
			if ok:
				var p: Vector2i = _free_spot(n, pending_b)
				n.issue_command("build_building", 0, { "type": id, "owner": 0, "x": p.x, "y": p.y }, 1)
				pending_b[id] = p
		var in_prog: Dictionary = n.world_state.get_section("tech").get("players", {}).get("0", {}).get("in_progress", {})
		for tid in tids:
			if researched.has(tid) or in_prog.has(tid):
				continue
			var okt: bool = true
			for r in (techs[tid] as Dictionary).get("requires", []):
				okt = okt and researched.has(str(r))
			for rb in (techs[tid] as Dictionary).get("requires_buildings", []):
				okt = okt and done_types.has(str(rb))
			if okt:
				n.issue_command("research_tech", 0, { "owner": 0, "node_id": tid }, 1)
		if step % 5 == 0:
			for uid in uids:
				if (rec.spawned.get("0", {}) as Dictionary).has(uid):
					continue
				var okprod: bool = true
				for r in _req_buildings(units[uid]):
					okprod = okprod and done_types.has(str(r))
				for t in _req_tech(units[uid]):
					okprod = okprod and researched.has(str(t))
				if not okprod:
					continue
				var list: Dictionary = _buildings(n)
				var keys: Array = list.keys()
				keys.sort_custom(func(a, b): return int(a) < int(b))
				for k in keys:
					var b: Dictionary = list[k]
					if int(b.get("owner", -1)) == 0 and int(b.get("construction_remaining", 0)) <= 0 \
							and (b.get("buildable_units", []) as Array).has(uid) and (b.get("build_queue", []) as Array).size() < 2:
						n.issue_command("build_unit", 0, { "owner": 0, "building_id": int(b["id"]), "unit_type": uid }, 1)
						break
		n.run_ticks(50)
		for id in pending_b.keys():
			if _first_building_of(n, 0, id).is_empty():
				pending_b.erase(id)
		var all_done: bool = _completed_types(n, 0).size() >= bids.size() and _researched(n, 0).size() >= tids.size()
		for uid in uids:
			all_done = all_done and (rec.spawned.get("0", {}) as Dictionary).has(uid)
		if all_done:
			break
	var final_types: Array = _completed_types(n, 0)
	var miss_b: Array = []
	for id in bids:
		if not final_types.has(id):
			miss_b.append(id)
	var miss_t: Array = []
	for tid in tids:
		if not _researched(n, 0).has(tid):
			miss_t.append(tid)
	var miss_u: Array = []
	for uid in uids:
		if not (rec.spawned.get("0", {}) as Dictionary).has(uid):
			miss_u.append(uid)
	_ok(not bids.is_empty() and miss_b.is_empty(), "D01", "player can complete every fr_ building via commands %s" % str(miss_b))
	_ok(not tids.is_empty() and miss_t.is_empty(), "D02", "player can research every fr_ tech %s" % str(miss_t))
	_ok(not uids.is_empty() and miss_u.is_empty(), "D03", "player can produce every fr_ unit %s" % str(miss_u))
	_ok(miss_b.is_empty() and miss_t.is_empty() and miss_u.is_empty() and n.world_state.current_tick <= 20000, "D04",
		"full tree completed within 20000 ticks (tick %d)" % n.world_state.current_tick)
	var bad: Array = []
	for r in rec.reasons("economy.build_rejected") + rec.reasons("buildings.build_rejected") + rec.reasons("tech.research_rejected"):
		if r in ["unknown_unit", "unknown_building", "unknown_tech", "missing_prerequisite"]:
			bad.append(r)
	_ok(bad.is_empty(), "D05", "no unknown_*/missing_prerequisite rejections for orders whose prerequisites were met %s" % str(bad))


func _free_spot(n: Object, reserved: Dictionary) -> Vector2i:
	# Deterministic grid of build spots, 3 tiles apart, skipping occupied/reserved tiles.
	var ms: Dictionary = n.world_state.get_section("map")
	var w: int = int(ms.get("width", 0))
	var h: int = int(ms.get("height", 0))
	var used: Dictionary = {}
	for key in _buildings(n).keys():
		var b: Dictionary = _buildings(n)[key]
		used[Vector2i(int(b["x"]), int(b["y"]))] = true
	for key2 in _units(n).keys():
		var u: Dictionary = _units(n)[key2]
		used[Vector2i(int(u["x"]), int(u["y"]))] = true
	for rk in reserved.keys():
		used[reserved[rk]] = true
	for y in range(3, h - 2, 3):
		for x in range(3, w - 2, 3):
			var p: Vector2i = Vector2i(x, y)
			if abs(x - 6) <= 1 and abs(y - 6) <= 1:
				continue
			if not used.has(p):
				return p
	return Vector2i(1, 1)


# =============================================================================
# E. Map quality (natural, fair, connected)
# =============================================================================

func _e_maps() -> void:
	for sid in [DUEL_ID, FOUR_ID]:
		var n: Object = _full()
		var sc: Variant = n.data_loader.get_entry("scenarios", sid)
		_ok(sc is Dictionary, "E00." + sid, "scenario exists")
		if not (sc is Dictionary):
			continue
		var s: Dictionary = sc
		var want_players: int = 2 if sid == DUEL_ID else 4
		var ps: Array = s.get("players", [])
		_ok(ps.size() == want_players, "E01." + sid, "%d players" % want_players)
		var human0: bool = false
		var ai_rest: bool = true
		for p in ps:
			if int(p.get("owner", -1)) == 0:
				human0 = bool(p.get("is_human", false))
			elif bool(p.get("is_human", false)):
				ai_rest = false
		_ok(human0 and ai_rest, "E02." + sid, "owner 0 is human, others AI")
		var rules: Dictionary = s.get("rules", {})
		_ok(bool(rules.get("full_ai", false)) and int(rules.get("pop_cap", 0)) >= 20 and int(rules.get("pop_cap", 0)) <= 60,
			"E03." + sid, "rules.full_ai=true, 20<=pop_cap<=60 %s" % str(rules))
		_ok(str(s.get("hq_type", "")) == HQ_TYPE and (s.get("map", {}) as Dictionary).has("rows"), "E04." + sid,
			"hq_type=fr_citadel and ASCII map.rows")
		ScenarioLoader.apply_scenario(n, s)
		var ms: Dictionary = n.world_state.get_section("map")
		var w: int = int(ms.get("width", 0))
		var h: int = int(ms.get("height", 0))
		var tiles: Array = []
		for t in ms.get("tiles", []):
			tiles.append(int(t))
		var minw: int = 48 if sid == DUEL_ID else 64
		var minh: int = 32 if sid == DUEL_ID else 48
		_ok(w >= minw and h >= minh and tiles.size() == w * h, "E05." + sid, "size >= %dx%d (got %dx%d)" % [minw, minh, w, h])
		if tiles.size() != w * h or w == 0:
			continue
		var cnt: Array = [0, 0, 0, 0]
		for t in tiles:
			if t >= 0 and t < 4:
				cnt[t] += 1
		var total: float = float(w * h)
		var fw: float = cnt[2] / total
		var ff: float = cnt[3] / total
		var fr: float = cnt[1] / total
		_ok(fw >= 0.05 and fw <= 0.25, "E06." + sid, "water 5..25%% (%.1f%%)" % (fw * 100.0))
		_ok(ff >= 0.08 and ff <= 0.30, "E07." + sid, "forest 8..30%% (%.1f%%)" % (ff * 100.0))
		_ok(fr >= 0.02 and fr <= 0.15, "E08." + sid, "rock 2..15%% (%.1f%%)" % (fr * 100.0))
		var clustered: int = 0
		for y in range(h):
			for x in range(w):
				if tiles[y * w + x] != 3:
					continue
				var nb: int = 0
				for d in [Vector2i(1, 0), Vector2i(-1, 0), Vector2i(0, 1), Vector2i(0, -1)]:
					var xx: int = x + d.x
					var yy: int = y + d.y
					if xx >= 0 and yy >= 0 and xx < w and yy < h and tiles[yy * w + xx] == 3:
						nb += 1
				if nb >= 2:
					clustered += 1
		_ok(cnt[3] > 0 and float(clustered) / float(cnt[3]) >= 0.65, "E09." + sid,
			"forest grows in clusters (%.0f%% have >=2 forest neighbours)" % (100.0 * clustered / max(1, cnt[3])))
		var wcomp: Array = _components(tiles, w, h, 2)
		_ok(not wcomp.is_empty() and float(wcomp[0]) / float(max(1, cnt[2])) >= 0.40, "E10." + sid,
			"water forms a real body (largest components %s of %d)" % [str(wcomp.slice(0, 3)), cnt[2]])
		var gcomp: Array = _components(tiles, w, h, 0)
		_ok(not gcomp.is_empty() and float(gcomp[0]) / float(max(1, cnt[0])) >= 0.85, "E11." + sid,
			"ground is one connected land (largest %d of %d)" % [int(gcomp[0]) if not gcomp.is_empty() else 0, cnt[0]])
		var hqs: Array = []
		var keys: Array = _buildings(n).keys()
		keys.sort_custom(func(a, b): return int(a) < int(b))
		for k in keys:
			var b: Dictionary = _buildings(n)[k]
			if str(b.get("type", "")) == HQ_TYPE:
				hqs.append(Vector2i(int(b["x"]), int(b["y"])))
		_ok(hqs.size() == want_players, "E12." + sid, "one fr_citadel per player (%d)" % hqs.size())
		var lens: Array = []
		var connected: bool = hqs.size() >= 2
		for i in range(hqs.size()):
			var best: int = 1 << 30
			for j in range(hqs.size()):
				if i == j:
					continue
				var path: Array = PathService.find_path(w, h, tiles, _open_near(tiles, w, h, hqs[i]), _open_near(tiles, w, h, hqs[j]))
				if path.is_empty():
					connected = false
				else:
					best = min(best, path.size())
			lens.append(best)
		_ok(connected, "E13." + sid, "every citadel reaches every other citadel by land")
		var lmin: int = 1 << 30
		var lmax: int = 0
		for l in lens:
			lmin = min(lmin, int(l))
			lmax = max(lmax, int(l))
		_ok(connected and lmax > 0 and float(lmin) / float(lmax) >= 0.85, "E14." + sid,
			"fair: nearest-enemy path lengths within 15%% %s" % str(lens))
		_ok(connected and lmin >= (30 if sid == DUEL_ID else 25), "E15." + sid, "citadels are far apart (min path %d)" % lmin)
		var room: Array = []
		for hq in hqs:
			var g: int = 0
			for y in range(max(0, hq.y - 6), min(h, hq.y + 7)):
				for x in range(max(0, hq.x - 6), min(w, hq.x + 7)):
					if abs(x - hq.x) + abs(y - hq.y) <= 6 and tiles[y * w + x] == 0:
						g += 1
			room.append(g)
		var rmin: int = 1 << 30
		var rmax: int = 0
		for r in room:
			rmin = min(rmin, int(r))
			rmax = max(rmax, int(r))
		_ok(rmax > 0 and float(rmin) / float(rmax) >= 0.85 and rmin >= 60, "E16." + sid,
			"fair build room: ground within radius 6 of each citadel >=60 and within 15%% %s" % str(room))


func _open_near(tiles: Array, w: int, h: int, p: Vector2i) -> Vector2i:
	for d in [Vector2i(0, 0), Vector2i(1, 0), Vector2i(0, 1), Vector2i(-1, 0), Vector2i(0, -1), Vector2i(1, 1), Vector2i(-1, -1)]:
		var q: Vector2i = p + d
		if q.x >= 0 and q.y >= 0 and q.x < w and q.y < h and tiles[q.y * w + q.x] == 0:
			return q
	return p


func _components(tiles: Array, w: int, h: int, terrain: int) -> Array:
	var seen: Dictionary = {}
	var sizes: Array = []
	for i in range(tiles.size()):
		if tiles[i] != terrain or seen.has(i):
			continue
		var stack: Array = [i]
		seen[i] = true
		var size: int = 0
		while not stack.is_empty():
			var c: int = int(stack.pop_back())
			size += 1
			var cx: int = c % w
			var cy: int = c / w
			for d in [Vector2i(1, 0), Vector2i(-1, 0), Vector2i(0, 1), Vector2i(0, -1)]:
				var xx: int = cx + d.x
				var yy: int = cy + d.y
				if xx < 0 or yy < 0 or xx >= w or yy >= h:
					continue
				var ni: int = yy * w + xx
				if not seen.has(ni) and tiles[ni] == terrain:
					seen[ni] = true
					stack.append(ni)
		sizes.append(size)
	sizes.sort()
	sizes.reverse()
	return sizes


# =============================================================================
# F. AI plays the mod: diverse, decisive, deterministic
# =============================================================================

func _ai_scenario(n: Object, sid: String) -> Dictionary:
	var sc: Variant = n.data_loader.get_entry("scenarios", sid)
	if not (sc is Dictionary):
		return {}
	var s: Dictionary = (sc as Dictionary).duplicate(true)
	for p in s.get("players", []):
		p["is_human"] = false
		p["smart"] = true
	return s


func _sample(n: Object, acc: Dictionary) -> void:
	var list: Dictionary = _buildings(n)
	for k in list.keys():
		var b: Dictionary = list[k]
		if int(b.get("construction_remaining", 0)) <= 0 and int(b.get("health", 0)) > 0:
			var o: String = str(int(b.get("owner", -1)))
			if not acc.has(o):
				acc[o] = {}
			acc[o][str(b.get("type", ""))] = true


func _f_ai() -> void:
	var n: Object = _full()
	var s: Dictionary = _ai_scenario(n, DUEL_ID)
	if s.is_empty():
		for cid in ["F01", "F02", "F03", "F04", "F05", "F06", "F07", "F08", "F09", "F10"]:
			_ok(false, cid, "scenario %s missing" % DUEL_ID)
		return
	ScenarioLoader.apply_scenario(n, s)
	var rec: Rec = _rec(n)
	var acc: Dictionary = {}
	var vic: Object = n.get_module("victory")
	var t0: int = Time.get_ticks_msec()
	while n.world_state.current_tick < 18000 and not vic.is_over():
		n.run_ticks(100)
		_sample(n, acc)
	var ms: int = Time.get_ticks_msec() - t0
	print("T006_INFO duel ticks=%d ms=%d over=%s winner=%d" % [n.world_state.current_tick, ms, str(vic.is_over()), vic.winner()])
	_ok(vic.is_over() and vic.winner() >= 0, "F01", "AI-vs-AI duel on %s ends with a winner before tick 18000 (tick %d)" % [DUEL_ID, n.world_state.current_tick])
	var w: String = str(vic.winner())
	var wb: int = (acc.get(w, {}) as Dictionary).size()
	var wu: int = (rec.spawned.get(w, {}) as Dictionary).size()
	var wt: int = (rec.techs.get(w, {}) as Dictionary).size()
	_ok(wb >= 7, "F02", "duel winner completed >= 7 building types (%d %s)" % [wb, str((acc.get(w, {}) as Dictionary).keys())])
	_ok(wu >= 6, "F03", "duel winner produced >= 6 unit types (%d %s)" % [wu, str((rec.spawned.get(w, {}) as Dictionary).keys())])
	_ok(wt >= 4, "F04", "duel winner researched >= 4 techs (%d)" % wt)
	_ok(n.world_state.current_tick >= 3000, "F05", "duel is not a rush-over before tick 3000 (tick %d)" % n.world_state.current_tick)
	_ok(ms <= 300000, "F06", "duel simulation time <= 300 s (%d ms)" % ms)
	var rej: int = rec.count("buildings.build_rejected") + rec.count("economy.build_rejected") + rec.count("tech.research_rejected")
	_ok(rej <= 400, "F07", "AI does not spam rejected orders (%d rejections)" % rej)

	var n4: Object = _full()
	var s4: Dictionary = _ai_scenario(n4, FOUR_ID)
	if s4.is_empty():
		for cid in ["F08", "F09", "F10"]:
			_ok(false, cid, "scenario %s missing" % FOUR_ID)
		return
	ScenarioLoader.apply_scenario(n4, s4)
	var rec4: Rec = _rec(n4)
	var acc4: Dictionary = {}
	t0 = Time.get_ticks_msec()
	for i in range(90):
		n4.run_ticks(100)
		_sample(n4, acc4)
	print("T006_INFO four ticks=9000 ms=%d" % (Time.get_ticks_msec() - t0))
	var good: int = 0
	var report: Array = []
	for o in range(4):
		var ob: int = (acc4.get(str(o), {}) as Dictionary).size()
		var ou: int = (rec4.spawned.get(str(o), {}) as Dictionary).size()
		var ot: int = (rec4.techs.get(str(o), {}) as Dictionary).size()
		report.append("%d:b%d/u%d/t%d" % [o, ob, ou, ot])
		if ob >= 6 and ou >= 5 and ot >= 3:
			good += 1
	_ok(good >= 3, "F08", ">= 3 of 4 AIs reach 6 building types, 5 unit types, 3 techs by tick 9000 %s" % str(report))

	var ha: int = _run_hash(FOUR_ID, 2000, -1)
	var hb: int = _run_hash(FOUR_ID, 2000, -1)
	_ok(ha == hb and ha != 0, "F09", "four-player AI match is deterministic (%d == %d)" % [ha, hb])
	var hc: int = _run_hash(FOUR_ID, 2000, 900)
	_ok(hc == ha, "F10", "save/load at tick 900 then continue == uninterrupted (%d == %d)" % [hc, ha])


func _run_hash(sid: String, ticks: int, cut: int) -> int:
	var a: Object = _full()
	var s: Dictionary = _ai_scenario(a, sid)
	if s.is_empty():
		return 0
	ScenarioLoader.apply_scenario(a, s)
	if cut < 0:
		a.run_ticks(ticks)
		return StateHasher.hash_world(a.world_state)
	a.run_ticks(cut)
	var sa: SaveSystem = SaveSystem.new()
	sa.setup(a)
	var text: String = JSON.stringify(sa.build_snapshot())
	var b: Object = _full()
	ScenarioLoader.apply_scenario(b, _ai_scenario(b, sid))
	var sb: SaveSystem = SaveSystem.new()
	sb.setup(b)
	var parsed: Variant = JSON.parse_string(text)
	if not (parsed is Dictionary) or not sb.apply_snapshot(parsed):
		return -1
	b.run_ticks(ticks - cut)
	return StateHasher.hash_world(b.world_state)


# =============================================================================
# G. HUD logic, rendering, smoke wiring, docs, tests
# =============================================================================

class FakeCanvas extends RefCounted:
	var calls: Array = []

	func draw_rect(rect, color, filled = true, width = -1.0, aa = false) -> void:
		calls.append(["rect", color, filled])

	func draw_circle(pos, radius, color, filled = true, width = -1.0, aa = false) -> void:
		calls.append(["circle", color])

	func draw_colored_polygon(points, color, uvs = PackedVector2Array(), texture = null) -> void:
		calls.append(["poly", color])

	func draw_polygon(points, colors, uvs = PackedVector2Array(), texture = null) -> void:
		calls.append(["polys", colors[0] if colors.size() > 0 else Color()])

	func draw_line(a, b, color, width = -1.0, aa = false) -> void:
		calls.append(["line", color])

	func draw_polyline(points, color, width = -1.0, aa = false) -> void:
		calls.append(["polyline", color])

	func draw_texture_rect(tex, rect, tile, modulate = Color(1, 1, 1), transpose = false) -> void:
		calls.append(["tex", modulate])

	func draw_arc(center, radius, a0, a1, count, color, width = -1.0, aa = false) -> void:
		calls.append(["arc", color])

	func first_fill() -> Color:
		for c in calls:
			if c[0] == "rect" and bool(c[2]):
				return c[1]
			if c[0] in ["circle", "poly", "polys", "tex"]:
				return c[1]
		return Color(0, 0, 0, 0)


func _arg_count(script_path: String, method: String) -> int:
	var s: Script = load(script_path)
	if s == null:
		return -1
	for m in s.get_script_method_list():
		if str(m["name"]) == method:
			return (m["args"] as Array).size()
	return -1


func _g_ui_render_docs() -> void:
	var hl: Script = load("res://ui/shared/hud_logic_util.gd")
	var names: Array = []
	if hl != null:
		for m in hl.get_script_method_list():
			names.append(str(m["name"]))
	for fn in ["building_menu", "production_menu", "resource_lines"]:
		_ok(names.has(fn), "G01." + fn, "HudLogicUtil.%s exists" % fn)
	if names.has("building_menu"):
		var bcat: Dictionary = {
			"fr_b": { "id": "fr_b", "cost": { GOLD: 100 }, "requires": { "buildings": ["fr_a"] } },
			"fr_a": { "id": "fr_a", "cost": { GOLD: 50 } },
			"fr_c": { "id": "fr_c", "cost": { GOLD: 500, ENERGY: 5 }, "requires": { "tech": ["fr_t"] } },
		}
		var menu: Variant = hl.call("building_menu", bcat, ["fr_a"], [], { GOLD: 120 })
		var ok: bool = menu is Array and (menu as Array).size() == 3
		if ok:
			var ids: Array = []
			for e in menu:
				ids.append(str(e.get("id", "")))
			ok = ids == ["fr_a", "fr_b", "fr_c"]
			ok = ok and bool(menu[0]["affordable"]) and (menu[0]["missing"] as Array).is_empty()
			ok = ok and bool(menu[1]["affordable"]) and (menu[1]["missing"] as Array).is_empty()
			ok = ok and not bool(menu[2]["affordable"]) and menu[2]["missing"] == ["tech:fr_t"]
		_ok(ok, "G02", "building_menu returns sorted {id, affordable, missing} (got %s)" % str(menu))
	else:
		_ok(false, "G02", "needs building_menu")
	if names.has("production_menu"):
		var ucat: Dictionary = {
			"fr_u1": { "id": "fr_u1", "cost": { GOLD: 10 } },
			"fr_u2": { "id": "fr_u2", "cost": { GOLD: 10, ENERGY: 50 }, "requires": { "tech": ["fr_t"] } },
		}
		var pm: Variant = hl.call("production_menu", { "buildable_units": ["fr_u2", "fr_u1"] }, ucat, [], [], { GOLD: 20, ENERGY: 10 })
		var ok2: bool = pm is Array and (pm as Array).size() == 2
		if ok2:
			ok2 = str(pm[0]["id"]) == "fr_u1" and bool(pm[0]["affordable"]) and str(pm[1]["id"]) == "fr_u2" \
					and not bool(pm[1]["affordable"]) and pm[1]["missing"] == ["tech:fr_t"]
		_ok(ok2, "G03", "production_menu returns sorted entries with affordability + missing (got %s)" % str(pm))
	else:
		_ok(false, "G03", "needs production_menu")
	if names.has("resource_lines"):
		var rl: Variant = hl.call("resource_lines", { ENERGY: 7, GOLD: 30 })
		_ok(rl is Array and (rl as Array).size() == 2 and str(rl[0]["id"]) == GOLD and int(rl[0]["amount"]) == 30
				and str(rl[1]["id"]) == ENERGY and int(rl[1]["amount"]) == 7, "G04",
			"resource_lines returns [{id, amount}] with resource_basic first, then others sorted (got %s)" % str(rl))
	else:
		_ok(false, "G04", "needs resource_lines")

	for path in ["res://ui/desktop/desktop_hud.gd", "res://ui/mobile/game_hud.gd"]:
		var text: String = FileAccess.get_file_as_string(path)
		var f: String = path.get_file()
		_ok(text.contains("HudLogicUtil.building_menu("), "G05." + f, "%s uses HudLogicUtil.building_menu" % f)
		_ok(text.contains("HudLogicUtil.production_menu("), "G06." + f, "%s uses HudLogicUtil.production_menu" % f)
		_ok(text.contains("HudLogicUtil.resource_lines("), "G07." + f, "%s uses HudLogicUtil.resource_lines" % f)
		_ok(text.contains("\"build_building\""), "G08." + f, "%s issues build_building player commands" % f)
		_ok(text.contains("\"research_tech\""), "G09." + f, "%s issues research_tech player commands" % f)

	for sp in ["res://render/style_simple/style_simple.gd", "res://render/style_sprite/style_sprite.gd",
			"res://render/style_detailed/style_detailed.gd"]:
		var fname: String = sp.get_file()
		var ac: int = _arg_count(sp, "draw_tile")
		_ok(ac >= 5, "G10." + fname, "%s draw_tile(canvas, rect, terrain_id, x, y) (args %d)" % [fname, ac])
		if ac < 5:
			for cid in ["G11.", "G12.", "G13."]:
				_ok(false, cid + fname, "needs 5-arg draw_tile")
			continue
		var style: Object = load(sp).new()
		var ground: Dictionary = {}
		for y in range(8):
			for x in range(8):
				var c: FakeCanvas = FakeCanvas.new()
				style.call("draw_tile", c, Rect2(0, 0, 32, 32), 0, x, y)
				ground[c.first_fill().to_html()] = true
		_ok(ground.size() >= 3, "G11." + fname, "ground has >= 3 natural colour variants over 8x8 tiles (%d)" % ground.size())
		var cf: FakeCanvas = FakeCanvas.new()
		style.call("draw_tile", cf, Rect2(0, 0, 32, 32), 3, 1, 1)
		var cg: FakeCanvas = FakeCanvas.new()
		style.call("draw_tile", cg, Rect2(0, 0, 32, 32), 0, 1, 1)
		_ok(cf.calls.size() >= 3 and cf.first_fill() != cg.first_fill(), "G12." + fname,
			"forest tile draws distinct detailed art (%d calls)" % cf.calls.size())
		var c1: FakeCanvas = FakeCanvas.new()
		var c2: FakeCanvas = FakeCanvas.new()
		style.call("draw_tile", c1, Rect2(0, 0, 32, 32), 0, 5, 3)
		style.call("draw_tile", c2, Rect2(0, 0, 32, 32), 0, 5, 3)
		_ok(c1.first_fill() == c2.first_fill() and c1.calls.size() == c2.calls.size(), "G13." + fname,
			"tile art is a pure function of (terrain, x, y)")
	var ra: String = FileAccess.get_file_as_string("res://render/render_adapter.gd")
	var rx: RegEx = RegEx.new()
	rx.compile("draw_tile\\(self,[^,)]+,[^,)]+,[^,)]+,[^,)]+\\)")
	_ok(rx.search(ra) != null, "G14", "render_adapter passes tile x,y to style.draw_tile")
	var mini: String = FileAccess.get_file_as_string("res://ui/shared/minimap.gd")
	_ok(mini.to_lower().contains("forest"), "G15", "minimap knows forest terrain")

	var smoke: String = FileAccess.get_file_as_string("res://tools/game_smoke.gd")
	_ok(smoke.contains(DUEL_ID), "G16", "tools/game_smoke.gd also smokes %s" % DUEL_ID)
	var ci: String = FileAccess.get_file_as_string("res://.github/workflows/ci.yml")
	_ok(ci.contains("tests/acceptance/t006_acceptance.gd"), "G17", "CI runs the T006 acceptance checker")

	var runner: String = FileAccess.get_file_as_string("res://tests/test_runner.gd")
	var rxt: RegEx = RegEx.new()
	rxt.compile("(?m)^func (test_t006_[a-z0-9_]+)\\(")
	var found: Array = rxt.search_all(runner)
	var nt: int = found.size()
	_ok(nt >= 25, "G18", ">= 25 test_t006_* functions in tests/test_runner.gd (%d)" % nt)
	var called: int = 0
	for m in found:
		var fname2: String = m.get_string(1)
		var crx: RegEx = RegEx.new()
		crx.compile("(?m)^\\s+" + fname2 + "\\(\\)\\s*$")
		if crx.search(runner) != null:
			called += 1
	_ok(nt > 0 and called == nt, "G19", "every test_t006_* is called (%d/%d)" % [called, nt])
	var vac: int = 0
	var brx: RegEx = RegEx.new()
	brx.compile("(?ms)^func test_t006_[a-z0-9_]+\\(.*?(?=^func |\\z)")
	for body in brx.search_all(runner):
		if body.get_string().contains("_check(true"):
			vac += 1
	_ok(nt > 0 and vac == 0, "G20", "no vacuous _check(true inside test_t006_* bodies (%d)" % vac)

	var state: String = FileAccess.get_file_as_string("res://docs/ai/PROJECT_STATE.md")
	_ok(state.contains("T006") and state.contains("frontier") and state.contains("T006_SUMMARY pass="), "G21",
		"docs/ai/PROJECT_STATE.md records T006 (frontier) with the final acceptance summary line")
	var dec: String = FileAccess.get_file_as_string("res://docs/ai/DECISIONS.md")
	_ok(dec.contains("DEC-017") and dec.contains("DEC-018"), "G22", "docs/ai/DECISIONS.md has DEC-017 and DEC-018")
	_ok(FileAccess.file_exists("res://docs/mods/frontier.md"), "G23", "docs/mods/frontier.md (design + tech tree + balance table) exists")
